package POJO;
// Generated 2016-12-07 00:35:26 by Hibernate Tools 4.3.1



/**
 * Adres generated by hbm2java
 */
public class Adres  implements java.io.Serializable {


     private int idAdresu;
     private String ulica;
     private String nrDomu;
     private Integer nrLokalu;
     private String kodPocztowy;
     private String miejscowosc;

    public Adres() {
    }

	
    public Adres(int idAdresu) {
        this.idAdresu = idAdresu;
    }
    public Adres(int idAdresu, String ulica, String nrDomu, Integer nrLokalu, String kodPocztowy, String miejscowosc) {
       this.idAdresu = idAdresu;
       this.ulica = ulica;
       this.nrDomu = nrDomu;
       this.nrLokalu = nrLokalu;
       this.kodPocztowy = kodPocztowy;
       this.miejscowosc = miejscowosc;
    }
   
    public int getIdAdresu() {
        return this.idAdresu;
    }
    
    public void setIdAdresu(int idAdresu) {
        this.idAdresu = idAdresu;
    }
    public String getUlica() {
        return this.ulica;
    }
    
    public void setUlica(String ulica) {
        this.ulica = ulica;
    }
    public String getNrDomu() {
        return this.nrDomu;
    }
    
    public void setNrDomu(String nrDomu) {
        this.nrDomu = nrDomu;
    }
    public Integer getNrLokalu() {
        return this.nrLokalu;
    }
    
    public void setNrLokalu(Integer nrLokalu) {
        this.nrLokalu = nrLokalu;
    }
    public String getKodPocztowy() {
        return this.kodPocztowy;
    }
    
    public void setKodPocztowy(String kodPocztowy) {
        this.kodPocztowy = kodPocztowy;
    }
    public String getMiejscowosc() {
        return this.miejscowosc;
    }
    
    public void setMiejscowosc(String miejscowosc) {
        this.miejscowosc = miejscowosc;
    }




}


