package POJO;
// Generated 2016-12-07 14:38:12 by Hibernate Tools 4.3.1



/**
 * Film generated by hbm2java
 */
public class Film  implements java.io.Serializable {


     private int idFilmu;
     private String tytul;
     private Short rokProdukcji;
     private Long ilosc;
     private Integer idRezysera;
     private Integer idNosnika;

    public Film() {
    }

	
    public Film(int idFilmu, String tytul) {
        this.idFilmu = idFilmu;
        this.tytul = tytul;
    }
    public Film(int idFilmu, String tytul, Short rokProdukcji, Long ilosc, Integer idRezysera, Integer idNosnika) {
       this.idFilmu = idFilmu;
       this.tytul = tytul;
       this.rokProdukcji = rokProdukcji;
       this.ilosc = ilosc;
       this.idRezysera = idRezysera;
       this.idNosnika = idNosnika;
    }
   
    public int getIdFilmu() {
        return this.idFilmu;
    }
    
    public void setIdFilmu(int idFilmu) {
        this.idFilmu = idFilmu;
    }
    public String getTytul() {
        return this.tytul;
    }
    
    public void setTytul(String tytul) {
        this.tytul = tytul;
    }
    public Short getRokProdukcji() {
        return this.rokProdukcji;
    }
    
    public void setRokProdukcji(Short rokProdukcji) {
        this.rokProdukcji = rokProdukcji;
    }
    public Long getIlosc() {
        return this.ilosc;
    }
    
    public void setIlosc(Long ilosc) {
        this.ilosc = ilosc;
    }
    public Integer getIdRezysera() {
        return this.idRezysera;
    }
    
    public void setIdRezysera(Integer idRezysera) {
        this.idRezysera = idRezysera;
    }
    public Integer getIdNosnika() {
        return this.idNosnika;
    }
    
    public void setIdNosnika(Integer idNosnika) {
        this.idNosnika = idNosnika;
    }




}


