package POJO;
// Generated 2016-12-07 00:35:26 by Hibernate Tools 4.3.1



/**
 * GatunekFilm generated by hbm2java
 */
public class GatunekFilm  implements java.io.Serializable {


     private GatunekFilmId id;

    public GatunekFilm() {
    }

    public GatunekFilm(GatunekFilmId id) {
       this.id = id;
    }
   
    public GatunekFilmId getId() {
        return this.id;
    }
    
    public void setId(GatunekFilmId id) {
        this.id = id;
    }




}


