package POJO;
// Generated 2016-12-06 23:33:50 by Hibernate Tools 4.3.1



/**
 * GatunekFilmId generated by hbm2java
 */
public class GatunekFilmId  implements java.io.Serializable {


     private int idGatunku;
     private int idFilmu;

    public GatunekFilmId() {
    }

    public GatunekFilmId(int idGatunku, int idFilmu) {
       this.idGatunku = idGatunku;
       this.idFilmu = idFilmu;
    }
   
    public int getIdGatunku() {
        return this.idGatunku;
    }
    
    public void setIdGatunku(int idGatunku) {
        this.idGatunku = idGatunku;
    }
    public int getIdFilmu() {
        return this.idFilmu;
    }
    
    public void setIdFilmu(int idFilmu) {
        this.idFilmu = idFilmu;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GatunekFilmId) ) return false;
		 GatunekFilmId castOther = ( GatunekFilmId ) other; 
         
		 return (this.getIdGatunku()==castOther.getIdGatunku())
 && (this.getIdFilmu()==castOther.getIdFilmu());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdGatunku();
         result = 37 * result + this.getIdFilmu();
         return result;
   }   


}


