package POJO;
// Generated 2016-12-07 00:35:26 by Hibernate Tools 4.3.1



/**
 * Gatunek generated by hbm2java
 */
public class Gatunek  implements java.io.Serializable {


     private int idGatunku;
     private String nazwa;

    public Gatunek() {
    }

	
    public Gatunek(int idGatunku) {
        this.idGatunku = idGatunku;
    }
    public Gatunek(int idGatunku, String nazwa) {
       this.idGatunku = idGatunku;
       this.nazwa = nazwa;
    }
   
    public int getIdGatunku() {
        return this.idGatunku;
    }
    
    public void setIdGatunku(int idGatunku) {
        this.idGatunku = idGatunku;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }




}


