package POJO;
// Generated 2016-12-07 14:38:12 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Klient generated by hbm2java
 */
public class Klient  implements java.io.Serializable {


     private int idKlienta;
     private String imie;
     private String nazwisko;
     private Date dataUrodzenia;
     private Integer idAdresu;
     private String login;
     private String haslo;

    public Klient() {
    }

	
    public Klient(int idKlienta, String login, String haslo) {
        this.idKlienta = idKlienta;
        this.login = login;
        this.haslo = haslo;
    }
    public Klient(int idKlienta, String imie, String nazwisko, Date dataUrodzenia, Integer idAdresu, String login, String haslo) {
       this.idKlienta = idKlienta;
       this.imie = imie;
       this.nazwisko = nazwisko;
       this.dataUrodzenia = dataUrodzenia;
       this.idAdresu = idAdresu;
       this.login = login;
       this.haslo = haslo;
    }
   
    public int getIdKlienta() {
        return this.idKlienta;
    }
    
    public void setIdKlienta(int idKlienta) {
        this.idKlienta = idKlienta;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public Date getDataUrodzenia() {
        return this.dataUrodzenia;
    }
    
    public void setDataUrodzenia(Date dataUrodzenia) {
        this.dataUrodzenia = dataUrodzenia;
    }
    public Integer getIdAdresu() {
        return this.idAdresu;
    }
    
    public void setIdAdresu(Integer idAdresu) {
        this.idAdresu = idAdresu;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getHaslo() {
        return this.haslo;
    }
    
    public void setHaslo(String haslo) {
        this.haslo = haslo;
    }




}


