package POJO;
// Generated 2016-12-06 23:33:50 by Hibernate Tools 4.3.1



/**
 * Nosnik generated by hbm2java
 */
public class Nosnik  implements java.io.Serializable {


     private int idNosnika;
     private String typ;

    public Nosnik() {
    }

	
    public Nosnik(int idNosnika) {
        this.idNosnika = idNosnika;
    }
    public Nosnik(int idNosnika, String typ) {
       this.idNosnika = idNosnika;
       this.typ = typ;
    }
   
    public int getIdNosnika() {
        return this.idNosnika;
    }
    
    public void setIdNosnika(int idNosnika) {
        this.idNosnika = idNosnika;
    }
    public String getTyp() {
        return this.typ;
    }
    
    public void setTyp(String typ) {
        this.typ = typ;
    }




}


