package POJO;
// Generated 2016-12-06 23:33:50 by Hibernate Tools 4.3.1



/**
 * Oddzial generated by hbm2java
 */
public class Oddzial  implements java.io.Serializable {


     private int idOddzialu;
     private String nazwa;
     private String lokalizacja;

    public Oddzial() {
    }

	
    public Oddzial(int idOddzialu) {
        this.idOddzialu = idOddzialu;
    }
    public Oddzial(int idOddzialu, String nazwa, String lokalizacja) {
       this.idOddzialu = idOddzialu;
       this.nazwa = nazwa;
       this.lokalizacja = lokalizacja;
    }
   
    public int getIdOddzialu() {
        return this.idOddzialu;
    }
    
    public void setIdOddzialu(int idOddzialu) {
        this.idOddzialu = idOddzialu;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public String getLokalizacja() {
        return this.lokalizacja;
    }
    
    public void setLokalizacja(String lokalizacja) {
        this.lokalizacja = lokalizacja;
    }




}


