package POJO;
// Generated 2016-12-07 14:38:12 by Hibernate Tools 4.3.1



/**
 * Stanowisko generated by hbm2java
 */
public class Stanowisko  implements java.io.Serializable {


     private int idStanowiska;
     private String nazwa;
     private Integer pensja;

    public Stanowisko() {
    }

	
    public Stanowisko(int idStanowiska) {
        this.idStanowiska = idStanowiska;
    }
    public Stanowisko(int idStanowiska, String nazwa, Integer pensja) {
       this.idStanowiska = idStanowiska;
       this.nazwa = nazwa;
       this.pensja = pensja;
    }
   
    public int getIdStanowiska() {
        return this.idStanowiska;
    }
    
    public void setIdStanowiska(int idStanowiska) {
        this.idStanowiska = idStanowiska;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public Integer getPensja() {
        return this.pensja;
    }
    
    public void setPensja(Integer pensja) {
        this.pensja = pensja;
    }




}


