package POJO;
// Generated 2016-12-07 00:35:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transakcja generated by hbm2java
 */
public class Transakcja  implements java.io.Serializable {


     private int idTransakcji;
     private Integer idKlienta;
     private Integer idPracownika;
     private Integer idFilmu;
     private Date dataTransakcji;
     private String typ;

    public Transakcja() {
    }

	
    public Transakcja(int idTransakcji) {
        this.idTransakcji = idTransakcji;
    }
    public Transakcja(int idTransakcji, Integer idKlienta, Integer idPracownika, Integer idFilmu, Date dataTransakcji, String typ) {
       this.idTransakcji = idTransakcji;
       this.idKlienta = idKlienta;
       this.idPracownika = idPracownika;
       this.idFilmu = idFilmu;
       this.dataTransakcji = dataTransakcji;
       this.typ = typ;
    }
   
    public int getIdTransakcji() {
        return this.idTransakcji;
    }
    
    public void setIdTransakcji(int idTransakcji) {
        this.idTransakcji = idTransakcji;
    }
    public Integer getIdKlienta() {
        return this.idKlienta;
    }
    
    public void setIdKlienta(Integer idKlienta) {
        this.idKlienta = idKlienta;
    }
    public Integer getIdPracownika() {
        return this.idPracownika;
    }
    
    public void setIdPracownika(Integer idPracownika) {
        this.idPracownika = idPracownika;
    }
    public Integer getIdFilmu() {
        return this.idFilmu;
    }
    
    public void setIdFilmu(Integer idFilmu) {
        this.idFilmu = idFilmu;
    }
    public Date getDataTransakcji() {
        return this.dataTransakcji;
    }
    
    public void setDataTransakcji(Date dataTransakcji) {
        this.dataTransakcji = dataTransakcji;
    }
    public String getTyp() {
        return this.typ;
    }
    
    public void setTyp(String typ) {
        this.typ = typ;
    }




}


